# Generated by Django 4.2 on 2024-09-04 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMicu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='static/AppMicu/imagenes'),
        ),
    ]
